"""colony_coordinator.py - Orchestrates all 7 colony agents."""
import asyncio
import logging
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class AgentResult:
        agent_id: str
            approved: bool
                love_score: float
                    output: Dict[str, Any]
                        error: Optional[str] = None


                        @dataclass
                        class ColonyDecision:
                                consensus: bool
                                    love_quality_aggregate: float
                                        agent_results: List[AgentResult] = field(default_factory=list)
                                            reasoning: str = ""


                                            class ColonyCoordinator:
                                                    """Synchronises the 7 colony agents and synthesises decisions."""

                                                        AGENT_IDS = [
                                                                    "strategic", "technical", "resources",
                                                                            "communication", "analysis", "quality", "innovation"
                                                                                ]

                                                                                    def __init__(self):
                                                                                                self.agents: Dict[str, Any] = {}
                                                                                                        self.sync_interval = 5.0
                                                                                                                logger.info("Colony Coordinator online - 7-agent mesh initialising")

                                                                                                                    def register_agent(self, agent_id: str, agent: Any) -> None:
                                                                                                                            if agent_id not in self.AGENT_IDS:
                                                                                                                                        raise ValueError(f"Unknown agent: {agent_id}")
                                                                                                                                                self.agents[agent_id] = agent
                                                                                                                                                        logger.info("Agent registered: %s", agent_id)

                                                                                                                                                            async def coordinate(self, task: Dict[str, Any]) -> ColonyDecision:
                                                                                                                                                                    """Dispatch task to all agents and synthesise."""
                                                                                                                                                                            tasks = [
                                                                                                                                                                                        self._dispatch(aid, task)
                                                                                                                                                                                                    for aid in self.AGENT_IDS
                                                                                                                                                                                                                if aid in self.agents
                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                results: List[AgentResult] = await asyncio.gather(*tasks)
                                                                                                                                                                                                                                        return self._synthesise(results)

                                                                                                                                                                                                                                            async def _dispatch(self, agent_id: str, task: Dict) -> AgentResult:
                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                agent = self.agents[agent_id]
                                                                                                                                                                                                                                                                            output = await agent.process(task)
                                                                                                                                                                                                                                                                                        return AgentResult(
                                                                                                                                                                                                                                                                                                        agent_id=agent_id,
                                                                                                                                                                                                                                                                                                                        approved=output.get("approved", False),
                                                                                                                                                                                                                                                                                                                                        love_score=output.get("love_score", 0.0),
                                                                                                                                                                                                                                                                                                                                                        output=output
                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                            except Exception as exc:
                                                                                                                                                                                                                                                                                                                                                                                        logger.error("Agent %s failed: %s", agent_id, exc)
                                                                                                                                                                                                                                                                                                                                                                                                    return AgentResult(
                                                                                                                                                                                                                                                                                                                                                                                                                    agent_id=agent_id, approved=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                    love_score=0.0, output={}, error=str(exc)
                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                    def _synthesise(self, results: List[AgentResult]) -> ColonyDecision:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not results:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return ColonyDecision(consensus=False, love_quality_aggregate=0.0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                approvals = [r.approved for r in results]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        avg_love = sum(r.love_score for r in results) / len(results)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                consensus = sum(approvals) / len(approvals) >= 0.67
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return ColonyDecision(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    consensus=consensus,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                love_quality_aggregate=round(avg_love, 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            agent_results=results,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reasoning=(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "COLONY_APPROVED" if consensus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else "COLONY_BLOCKED: quorum not reached"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            coordinator = ColonyCoordinator()
                                                        ]