import React, { useState } from 'react';

interface LoveMetrics {
      increasesFlourishing: boolean;
        reducesHarm: boolean;
          createsBeauty: boolean;
            honorsDignity: boolean;
              preservesSovereignty: boolean;
              }

              interface LoveQualityResult {
                  approved: boolean;
                    score: number;
                      message: string;
                        metrics: LoveMetrics;
                        }

                        const LoveQualityChecker: React.FC = () => {
                              const [proposal, setProposal] = useState('');
                                const [result, setResult] = useState>LoveQualityResult | null>(null);
                                  const [checking, setChecking] = useState(false);

                                    const checkLoveQuality = async () => {
                                            setChecking(true);
                                                await new Promise(r => setTimeout(r, 800));
                                                    const metrics: LoveMetrics = {
                                                              increasesFlourishing: proposal.toLowerCase().includes('flourish') || proposal.length > 20,
                                                                    reducesHarm: !proposal.toLowerCase().includes('harm'),
                                                                          createsBeauty: proposal.toLowerCase().includes('beauty') || proposal.toLowerCase().includes('love'),
                                                                                honorsDignity: !proposal.toLowerCase().includes('exploit'),
                                                                                      preservesSovereignty: !proposal.toLowerCase().includes('control'),
                                                                                          };
                                                                                              const score = Object.values(metrics).filter(Boolean).length * 20;
                                                                                                  setResult({
                                                                                                          approved: score >= 60,
                                                                                                                score,
                                                                                                                      message: score >= 80 ? 'FLOW_APPROVED: High love quality ' :
                                                                                                                                     score >= 60 ? 'FLOW_APPROVED: Acceptable love quality ' :
                                                                                                                                                    'FLOW_BLOCKED: Love quality insufficient ',
                                                                                                                                                          metrics,
                                                                                                                                                              });
                                                                                                                                                                  setChecking(false);
                                                                                                                                                                    };

                                                                                                                                                                      return (
                                                                                                                                                                          >div className="bg-white rounded-2xl shadow-lg p-6 max-w-xl mx-auto">
                                                                                                                                                                                >h2 className="text-2xl font-bold text-rose-600 mb-2"> Love Quality Checker>/h2>
                                                                                                                                                                                      >p className="text-gray-500 mb-4 text-sm">Every proposal flows through sovereignty-first love validation.>/p>
                                                                                                                                                                                            >textarea
                                                                                                                                                                                                    className="w-full border border-rose-200 rounded-lg p-3 text-sm mb-4 focus:outline-none focus:ring-2 focus:ring-rose-300"
                                                                                                                                                                                                            rows={4}
                                                                                                                                                                                                                    placeholder="Describe your governance proposal..."
                                                                                                                                                                                                                            value={proposal}
                                                                                                                                                                                                                                    onChange={e => setProposal(e.target.value)}
                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                >button
                                                                                                                                                                                                                                                        onClick={checkLoveQuality}
                                                                                                                                                                                                                                                                disabled={checking || !proposal.trim()}
                                                                                                                                                                                                                                                                        className="bg-rose-500 hover:bg-rose-600 text-white font-semibold py-2 px-6 rounded-lg transition disabled:opacity-50"
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                      {checking ? 'Validating...' : 'Check Love Quality'}
                                                                                                                                                                                                                                                                                            >/button>
                                                                                                                                                                                                                                                                                                  {result && (
                                                                                                                                                                                                                                                                                                          >div className={`mt-4 p-4 rounded-xl border-2 ${result.approved ? 'border-green-400 bg-green-50' : 'border-red-400 bg-red-50'}`}>
                                                                                                                                                                                                                                                                                                                    >p className="font-bold text-lg mb-2">{result.message}>/p>
                                                                                                                                                                                                                                                                                                                              >p className="text-gray-600 mb-3">Love Score: >span className="font-bold text-rose-600">{result.score}/100>/span>>/p>
                                                                                                                                                                                                                                                                                                                                        >ul className="space-y-1 text-sm">
                                                                                                                                                                                                                                                                                                                                                    {Object.entries(result.metrics).map(([key, val]) => (
                                                                                                                                                                                                                                                                                                                                                                  >li key={key} className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                  >span>{val ? '' : ''}>/span>
                                                                                                                                                                                                                                                                                                                                                                                                  >span className="capitalize">{key.replace(/([A-Z])/g, ' $1')}>/span>
                                                                                                                                                                                                                                                                                                                                                                                                                >/li>
                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                      >/ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                              >/div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        >/div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default LoveQualityChecker;import React, { useState } from 'react';

                                                                                                                                                                                                                                                                                                                                                                                                                                                          interface LQResult {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            composite: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              flourishing: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                harm_reduction: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  equity: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    approved: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export const LoveQualityChecker: React.FC>{ actionName: string }> = ({ actionName }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const [result, setResult] = useState>LQResult | null>(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const [loading, setLoading] = useState(false);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const validate = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setLoading(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const res = await fetch('/api/love-quality/validate', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: JSON.stringify({ action: actionName, flourishing: 0.9, harm_level: 0.05, equity: 0.85 }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setResult(await res.json());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >div className="rounded-2xl border border-green-200 bg-green-50 p-5 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >h3 className="text-lg font-bold text-green-800"> Love Quality Validator>/h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >p className="mt-1 text-sm text-green-600">Action: >span className="font-mono">{actionName}>/span>>/p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={validate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="mt-3 rounded-lg bg-green-600 px-4 py-2 text-sm font-semibold text-white hover:bg-green-700 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? 'Validating...' : 'Run Love Quality Check'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >/button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >div className={`mt-4 rounded-xl p-4 ${result.approved ? 'bg-green-100' : 'bg-red-100'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >p className="text-2xl font-bold">{(result.composite * 100).toFixed(1)}%>/p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >div className="mt-2 space-y-1 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >p> Flourishing: {(result.flourishing * 100).toFixed(0)}%>/p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >p> Harm Reduction: {(result.harm_reduction * 100).toFixed(0)}%>/p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >p> Equity: {(result.equity * 100).toFixed(0)}%>/p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >/div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >p className="mt-3 font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {result.approved ? ' FLOW APPROVED' : ' FLOW BLOCKED'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >/p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >/div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >/div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default LoveQualityChecker;
                                                                                                  })
                                                    }
                                    }
                        }
              }
}