import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, StatusBar } from 'react-native';

interface AgentStatus {
      id: number;
        name: string;
          icon: string;
            status: 'ONLINE' | 'SYNCING' | 'OFFLINE';
              lastAction: string;
              }

              const AGENTS: AgentStatus[] = [
                  { id: 1, name: 'Strategic', icon: 'S', status: 'ONLINE', lastAction: 'Sovereignty audit complete' },
                    { id: 2, name: 'Technical', icon: 'T', status: 'ONLINE', lastAction: 'Aethel Grid nominal' },
                      { id: 3, name: 'Resources', icon: 'R', status: 'SYNCING', lastAction: 'VAPG data loading...' },
                        { id: 4, name: 'Communication', icon: 'C', status: 'ONLINE', lastAction: 'Colony mesh active' },
                          { id: 5, name: 'Analysis', icon: 'A', status: 'ONLINE', lastAction: 'Love quality: 0.91' },
                            { id: 6, name: 'Quality', icon: 'Q', status: 'ONLINE', lastAction: 'Threshold maintained' },
                              { id: 7, name: 'Innovation', icon: 'I', status: 'ONLINE', lastAction: 'New flow activated' },
                              ];

                              export default function ColonyHomeScreen() {
                                  const [loveScore, setLoveScore] = useState(0.91);
                                    const [flowStatus, setFlowStatus] = useState('FLOW_APPROVED');

                                      useEffect(() => {
                                            const interval = setInterval(() => {
                                                      setLoveScore(prev => Math.min(1, prev + (Math.random() - 0.48) * 0.01));
                                                          }, 3000);
                                                              return () => clearInterval(interval);
                                                                }, []);

                                                                  return (
                                                                      >View style={styles.container}>
                                                                            >StatusBar barStyle="light-content" backgroundColor="#1e1b4b" />
                                                                                  >View style={styles.header}>
                                                                                          >Text style={styles.colonyTitle}>COLONY 001>/Text>
                                                                                                  >Text style={styles.flowBadge}>{flowStatus}>/Text>
                                                                                                        >/View>
                                                                                                              >View style={styles.scoreCard}>
                                                                                                                      >Text style={styles.scoreLabel}>Love Quality Index>/Text>
                                                                                                                              >Text style={styles.scoreValue}>{(loveScore * 100).toFixed(1)}%>/Text>
                                                                                                                                      >View style={styles.scoreBar}>
                                                                                                                                                >View style={[styles.scoreBarFill, { width: `${loveScore * 100}%` as any }]} />
                                                                                                                                                        >/View>
                                                                                                                                                              >/View>
                                                                                                                                                                    >Text style={styles.sectionTitle}>7 Colony Agents>/Text>
                                                                                                                                                                          >ScrollView style={styles.agentList}>
                                                                                                                                                                                  {AGENTS.map(agent => (
                                                                                                                                                                                            >View key={agent.id} style={styles.agentCard}>
                                                                                                                                                                                                        >View style={styles.agentIcon}>
                                                                                                                                                                                                                      >Text style={styles.agentIconText}>{agent.icon}>/Text>
                                                                                                                                                                                                                                  >/View>
                                                                                                                                                                                                                                              >View style={styles.agentInfo}>
                                                                                                                                                                                                                                                            >Text style={styles.agentName}>{agent.name}>/Text>
                                                                                                                                                                                                                                                                          >Text style={styles.agentAction}>{agent.lastAction}>/Text>
                                                                                                                                                                                                                                                                                      >/View>
                                                                                                                                                                                                                                                                                                  >View style={[styles.statusDot,
                                                                                                                                                                                                                                                                                                                agent.status === 'ONLINE' ? styles.online :
                                                                                                                                                                                                                                                                                                                              agent.status === 'SYNCING' ? styles.syncing : styles.offline
                                                                                                                                                                                                                                                                                                                                          ]} />
                                                                                                                                                                                                                                                                                                                                                    >/View>
                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                  >/ScrollView>
                                                                                                                                                                                                                                                                                                                                                                      >/View>
                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                          container: { flex: 1, backgroundColor: '#0f0e17' },
                                                                                                                                                                                                                                                                                                                                                                            header: { backgroundColor: '#1e1b4b', padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                              colonyTitle: { color: '#a5b4fc', fontSize: 20, fontWeight: '700', letterSpacing: 2 },
                                                                                                                                                                                                                                                                                                                                                                                flowBadge: { color: '#4ade80', fontSize: 10, fontWeight: '700', backgroundColor: '#052e16', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
                                                                                                                                                                                                                                                                                                                                                                                  scoreCard: { margin: 16, backgroundColor: '#1e1b4b', borderRadius: 12, padding: 16 },
                                                                                                                                                                                                                                                                                                                                                                                    scoreLabel: { color: '#a5b4fc', fontSize: 12, marginBottom: 4 },
                                                                                                                                                                                                                                                                                                                                                                                      scoreValue: { color: '#fff', fontSize: 32, fontWeight: '700' },
                                                                                                                                                                                                                                                                                                                                                                                        scoreBar: { height: 6, backgroundColor: '#312e81', borderRadius: 3, marginTop: 8 },
                                                                                                                                                                                                                                                                                                                                                                                          scoreBarFill: { height: 6, backgroundColor: '#4ade80', borderRadius: 3 },
                                                                                                                                                                                                                                                                                                                                                                                            sectionTitle: { color: '#a5b4fc', fontSize: 14, fontWeight: '600', marginLeft: 16, marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                              agentList: { flex: 1, paddingHorizontal: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                agentCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1a1a2e', borderRadius: 10, padding: 12, marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                  agentIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#312e81', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                    agentIconText: { color: '#a5b4fc', fontWeight: '700', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                      agentInfo: { flex: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                        agentName: { color: '#fff', fontWeight: '600', fontSize: 14 },
                                                                                                                                                                                                                                                                                                                                                                                                          agentAction: { color: '#6b7280', fontSize: 11, marginTop: 2 },
                                                                                                                                                                                                                                                                                                                                                                                                            statusDot: { width: 10, height: 10, borderRadius: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                              online: { backgroundColor: '#4ade80' },
                                                                                                                                                                                                                                                                                                                                                                                                                syncing: { backgroundColor: '#fbbf24' },
                                                                                                                                                                                                                                                                                                                                                                                                                  offline: { backgroundColor: '#ef4444' },
                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                            })
                                      })
                              }
              ]
}