"""love_quality_engine.py  Core Love Quality Scoring Engine.
Measures flourishing, equity, regeneration for every governance action."""
from dataclasses import dataclass, field
from typing import List, Dict, Any
import math
import logging

logger = logging.getLogger(__name__)

LOVE_QUALITY_THRESHOLD = 0.85


@dataclass
class LoveQualityScore:
        flourishing_index: float = 0.0
            harm_reduction_score: float = 0.0
                beauty_coefficient: float = 0.0
                    equity_distribution: float = 0.0
                        regenerative_salience: float = 0.0
                            cooperation_factor: float = 0.0
                                raw_scores: Dict[str, float] = field(default_factory=dict)
                                
                                    @property
                                        def composite(self) -> float:
                                                    weights = {
                                                                    "flourishing": 0.25,
                                                                                "harm_reduction": 0.20,
                                                                                            "equity": 0.20,
                                                                                                        "regenerative": 0.15,
                                                                                                                    "cooperation": 0.12,
                                                                                                                                "beauty": 0.08,
                                                                                                                                        }
                                                                                                                                                return (
                                                                                                                                                            self.flourishing_index * weights["flourishing"] +
                                                                                                                                                                        self.harm_reduction_score * weights["harm_reduction"] +
                                                                                                                                                                                    self.equity_distribution * weights["equity"] +
                                                                                                                                                                                                self.regenerative_salience * weights["regenerative"] +
                                                                                                                                                                                                            self.cooperation_factor * weights["cooperation"] +
                                                                                                                                                                                                                        self.beauty_coefficient * weights["beauty"]
                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                    @property
                                                                                                                                                                                                                                        def approved(self) -> bool:
                                                                                                                                                                                                                                                return self.composite >= LOVE_QUALITY_THRESHOLD


                                                                                                                                                                                                                                                class LoveQualityEngine:
                                                                                                                                                                                                                                                    """Evaluates the love quality of governance decisions."""

                                                                                                                                                                                                                                                        def __init__(self, threshold: float = LOVE_QUALITY_THRESHOLD):
                                                                                                                                                                                                                                                                self.threshold = threshold
                                                                                                                                                                                                                                                                        logger.info("Love Quality Engine initialized  threshold=%.2f", threshold)

                                                                                                                                                                                                                                                                            def evaluate(self, action_data: Dict[str, Any]) -> LoveQualityScore:
                                                                                                                                                                                                                                                                                    """Score an action across all love-quality dimensions."""
                                                                                                                                                                                                                                                                                            score = LoveQualityScore(
                                                                                                                                                                                                                                                                                                        flourishing_index=self._score_flourishing(action_data),
                                                                                                                                                                                                                                                                                                                    harm_reduction_score=self._score_harm_reduction(action_data),
                                                                                                                                                                                                                                                                                                                                beauty_coefficient=self._score_beauty(action_data),
                                                                                                                                                                                                                                                                                                                                            equity_distribution=self._score_equity(action_data),
                                                                                                                                                                                                                                                                                                                                                        regenerative_salience=self._score_regenerative(action_data),
                                                                                                                                                                                                                                                                                                                                                                    cooperation_factor=self._score_cooperation(action_data),
                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                    score.raw_scores = {
                                                                                                                                                                                                                                                                                                                                                                                                "flourishing": score.flourishing_index,
                                                                                                                                                                                                                                                                                                                                                                                                            "harm_reduction": score.harm_reduction_score,
                                                                                                                                                                                                                                                                                                                                                                                                                        "beauty": score.beauty_coefficient,
                                                                                                                                                                                                                                                                                                                                                                                                                                    "equity": score.equity_distribution,
                                                                                                                                                                                                                                                                                                                                                                                                                                                "regenerative": score.regenerative_salience,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "cooperation": score.cooperation_factor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "composite": score.composite,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.info("LQ composite=%.3f approved=%s", score.composite, score.approved)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return score

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def _score_flourishing(self, d: Dict) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return min(1.0, float(d.get("flourishing", 0.5)))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def _score_harm_reduction(self, d: Dict) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        harm = float(d.get("harm_level", 0.0))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return max(0.0, 1.0 - harm)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def _score_beauty(self, d: Dict) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return min(1.0, float(d.get("beauty", 0.5)))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def _score_equity(self, d: Dict) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        distribution = d.get("distribution", [])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not distribution:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 0.5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mean = sum(distribution) / len(distribution)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            variance = sum((x - mean) ** 2 for x in distribution) / len(distribution)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gini = math.sqrt(variance) / (mean + 1e-9)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return max(0.0, 1.0 - gini)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def _score_regenerative(self, d: Dict) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return min(1.0, float(d.get("regenerative", 0.5)))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def _score_cooperation(self, d: Dict) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return min(1.0, float(d.get("cooperation", 0.5)))


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Singleton
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    engine = LoveQualityEngine()
                                                    }"""